Messages:
  noPermission: "&b[&cWbeIndustries&b] &eNo tienes permiso para hacer esto."
  reload: "&b[&cWbeIndustries&b] &eEl plugin se ha recargado con éxito."

Tabs:
  testtab:
    achievements:
      root:
        display:
          material: BEACON
          name: "Root achievement"
          # Solo puede ser TASK, GOAL O CHALLENGE
          frame: CHALLENGE
          toast: true
          announce: true
          x: 1
          y: 2
          description: "Test description"
        background: "textures/block/pink_glazed_terracotta.png"
      base:
        breakachievement:
          display:
            material: NETHERITE_PICKAXE
            name: "Break achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 2
            y: 2
            description: "Test description"
          parent: root
          maxProgression: 10
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: BREAK
            block: STONE
        craftachievement:
          display:
            material: CRAFTING_TABLE
            name: "Craft achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 3
            y: 2
            description: "Test description"
          parent: breakachievement
          maxProgression: 20
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: CRAFT
            item: STICK
        enchantachievement:
          display:
            material: ENCHANTING_TABLE
            name: "Enchant achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 4
            y: 2
            description: "Test description"
          parent: craftachievement
          maxProgression: 5
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: ENCHANT
            item: DIAMOND_SWORD
        joblevelachievement:
          display:
            material: DIAMOND_ORE
            name: "Job Level achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 5
            y: 2
            description: "Test description"
          parent: enchantachievement
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: JOBLEVEL
            job: minero
            level: 4
        killachievement:
          display:
            material: ZOMBIE_SPAWN_EGG
            name: "Kill achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 6
            y: 2
            description: "Test description"
          parent: joblevelachievement
          maxProgression: 5
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: KILL
            entity: ZOMBIE
        mcmmopowerlevelachievement:
          display:
            material: NETHER_STAR
            name: "mcMMO Power Level achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 7
            y: 2
            description: "Test description"
          parent: killachievement
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: MCMMOPOWERLEVEL
            level: 10
        mcmmoskillachievement:
          display:
            material: WHITE_BANNER
            name: "mcMMO Skill achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 8
            y: 2
            description: "Test description"
          parent: mcmmopowerlevelachievement
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: MCMMOSKILL
            skill: swords
            level: 10
        mmkillachievement:
          display:
            material: NETHERITE_SWORD
            name: "MMKill achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 9
            y: 2
            description: "Test description"
          parent: mcmmoskillachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: MMKILL
            mob: SkeletonKing
        placeachievement:
          display:
            material: SCAFFOLDING
            name: "Place achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 10
            y: 2
            description: "Test description"
          parent: mmkillachievement
          maxProgression: 20
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: PLACE
            block: SCAFFOLDING
        tradeachievement:
          display:
            material: EMERALD
            name: "Trade achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 11
            y: 2
            description: "Test description"
          parent: placeachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: TRADE
        fishingrarityachievement:
          display:
            material: FISHING_ROD
            name: "Fishing Rarity achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 12
            y: 2
            description: "Test description"
          parent: tradeachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: FISHINGRARITY
            rarity: mythic
        woodcuttingrarityachievement:
          display:
            material: NETHERITE_AXE
            name: "Woodcutting Rarity achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 13
            y: 2
            description: "Test description"
          parent: fishingrarityachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: WOODCUTTINGRARITY
            rarity: mythic
        completelabourachievement:
          display:
            material: PAPER
            name: "Complete Labour achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 14
            y: 2
            description: "Test description"
          parent: woodcuttingrarityachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: LABOUR
            rarity: common
        crystaluseachievement:
          display:
            material: EMERALD
            name: "Complete Labour achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 15
            y: 2
            description: "Test description"
          parent: completelabourachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: CRYSTAL
            rarity: common
        gemachievement:
          display:
            material: AMETHYST_SHARD
            name: "Gem achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 16
            y: 2
            description: "Test description"
          parent: crystaluseachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: GEM
        talismanachievement:
          display:
            material: HEAVY_CORE
            name: "Talisman achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 17
            y: 2
            description: "Test description"
          parent: gemachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: TALISMAN
        petachievement:
          display:
            material: WITCH_SPAWN_EGG
            name: "Pet achievement"
            # Solo puede ser TASK, GOAL O CHALLENGE
            frame: TASK
            toast: true
            announce: true
            x: 18
            y: 2
            description: "Test description"
          parent: talismanachievement
          maxProgression: 2
          rewards:
            - "give %player% diamond 2"
            - "msg %player% test"
          type:
            # Solo puede ser BREAK, CRAFT, ENCHANT, JOBLEVEL, KILL, MCMMOPOWERLEVEL, MCMMOSKILL, MMKILL, PLACE, CRATE, TRADE, FISHINGRARITY, WOODCUTTINGRARITY, LABOUR, CRYSTAL, GEM, TALISMAN, PET
            id: PET